/**
 * Created by nielinlin on 2018/4/19.
 */
window.interfaceValue = {
    orderStatus:{
        "0":'待支付',
        "10":'支付中',
        "20":'已支付',
        "30":'处理中',
        "35":'配送中',
        "40":'退款中',
        "50":'已完成',
        "51":'已开票',
        "60":'已退款',
        "70":'已取消'
    },
    payType :{
        '0':'微信','1':'支付宝','50':'线下'
    },
    orderWarn : {
        'NORMAL':'正常',
        'WARNING':'预警',
        'TIMEOUT':'超时'
    },
    orderType : {
        '0':'虚拟',
        '1':'实物'
    },
    yumiType:{
        0:"消费返遇米",
        1:"签到领遇米",
        2:"赠送遇米",
        3:"活动送遇米",
        50:"抢身份扣除遇米",
        51:"购物使用遇米"
    },
    shenfen:{
        "1":{
            name:"平民",
            headf:"shenfen/h1.jpg",
            head:"shenfen/h_1.jpg"
        },
        "2":{
            name:"狼人",
            headf:"shenfen/h2.jpg",
            head:"shenfen/h_2.jpg"
        },
        "3":{
            name:"预言家",
            headf:"shenfen/h3.jpg",
            head:"shenfen/h_3.jpg"
        },
        "4":{
            name:"女巫",
            headf:"shenfen/h4.jpg",
            head:"shenfen/h_4.jpg"
        },
        "5":{
            name:"猎人",
            headf:"shenfen/h5.jpg",
            head:"shenfen/h_5.jpg"
        },
        "6":{
            name:"守卫",
            headf:"shenfen/h6.jpg",
            head:"shenfen/h_6.jpg"
        },
        "7":{
            name:"狼王",
            headf:"shenfen/h7.jpg",
            head:"shenfen/h_7.jpg"
        },
        "8":{
            name:"白狼王",
            headf:"shenfen/h8.jpg",
            head:"shenfen/h_8.jpg"
        },
        "9":{
            name:"白痴",
            headf:"shenfen/h9.jpg",
            head:"shenfen/h_9.jpg"
        },
        "10":{
            name:"丘比特",
            headf:"shenfen/h10.jpg",
            head:"shenfen/h_10.jpg"
        },
        "11":{
            name:"盗贼",
            headf:"shenfen/h11.jpg",
            head:"shenfen/h_11.jpg"
        },
        "12":{
            name:"盗贼",
            headf:"shenfen/h11.jpg",
            head:"shenfen/h11.jpg"
        },
        "13":{
            name:"盗贼",
            headf:"shenfen/h11.jpg",
            head:"shenfen/h11.jpg"
        },
        "14":{
            name:"魔术师",
            headf:"shenfen/h14.jpg",
            head:"shenfen/h_14.jpg"
        },
        "15":{
            name:"盗贼",
            headf:"shenfen/h_11.jpg",
            head:"shenfen/h11.jpg"
        },
        "16":{
            name:"盗贼",
            headf:"shenfen/h11.jpg",
            head:"shenfen/h11.jpg"
        },
        "17":{
            name:"盗贼",
            headf:"shenfen/h11.jpg",
            head:"shenfen/h11.jpg"
        },
        "18":{
            name:"盗贼",
            headf:"shenfen/h11.jpg",
            head:"shenfen/h11.jpg"
        },
        "19":{
            name:"盗贼",
            headf:"shenfen/h11.jpg",
            head:"shenfen/h11.jpg"
        }
    }
}
